### ISSUE TITLE
More nuanced labeling

### ISSUE THREAD

**Issue by zrobertson466920** [safinahali/elicitation-graphs-static#7]
(predicted high risk vs labelled high risk)

**Comment by zrobertson466920** [comment]
*Change out-of-100 samples to out-of-10000 or bigger? - related to percentages?

**Comment by sohiniu** [comment]
The new text should read "predicted high/low risk" but since this is on the graphs which I don't know how to edit I'm adding @safinahali to this issue.

**Comment by safinahali** [comment]
This text is fixed. Labeled -> Predicted.
